### ISSUE TITLE
Quick :w reverts last change when used with `pretter-eslint`

### ISSUE THREAD

**Issue by pjg** [neoclide/coc-prettier#134] opened 2021-09-01 16:59 UTC
I make a change and quickly hit the combination for `:w`. What happens is that my change is reverted and shortly after pretter runs and "Formatted by prettier" message is being displayed.

It's hard to diagnose as it might be the result of my config/plugins/etc. but I was unable to trace it. I only know this happens after I tried switching to `prettier-eslint`.

When showing command debug for `prettier` I can see the `newText` is incorrect, with the reverted change.

**Comment by mkindred** [comment] 2021-11-19 19:03
I'm seeing the same issue. It was hard to diagnose because the delay needed to ensure a good save is pretty short. I thought that it might be some sort of plugin conflict or the result of my becoming more comfortable in vim (and therefore typing faster).

It has become enough of a problem that I finally decided to diagnose with a minimal install and .vimrc.

If I type `dd` and then `sdf` in quick succession, the line is deleted, but then it reappears as soon as prettier runs. If I run those two commands with ~500ms between them, they work as expected.

Similarly, if I type `u` and `sdf` in quick succession, the undo executes, but is then reverted when prettier runs.

~/.vimrc:
```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

inoremap df <ESC>
noremap sdf <ESC>:w<CR>
inoremap sdf <ESC>:w<CR>
```
~/.vim/coc-settings.json:
```
{
  "coc.preferences.formatOnSaveFiletypes": ["scss"],
}
```

**Comment by Mathieuu** [comment] 2022-01-01 23:26
I can confirm the problem. Steps to reproduce for me:
- Have prettier configured to run on file save
- In a .tsx file, insert multiple new lines by keeping the enter key pressed
- Go back to command mode by pressing <ESC> then immediately type `:w`

File gets messed up.

**Comment by chemzqm** [comment] 2022-01-12 17:39
Might be fixed by https://github.com/neoclide/coc.nvim/commit/4a1cc23b4d1a708eb0b887ef538b7e8dda36bf63, try latest coc.nvim

**Comment by twe4ked** [comment] 2022-01-13 04:46
Looks like this is fixed the issue for me, thanks @chemzqm!

**Comment by chemzqm** [comment] 2022-01-13 10:12
Open another issue with `:CocInfo` if you still experience this bug.

**Closed by chemzqm** 2022-01-13 10:12 UTC

**Comment by tklepzig** [comment] 2022-01-14 09:47
Seems to work for me as well, thx @chemzqm!

**Comment by bobwhitelock** [comment] 2022-01-14 14:38
Fixed for me too, thanks @chemzqm!

**Comment by Mathieuu** [comment] 2022-01-18 17:09
Fixed it for me too! Thanks
